---
title: "Research"
---

## Working Paper
##### Multi-Unit Ownership and Market Power: A Study of the Texas Hotel Industry [[Draft](Koh_JMP.pdf)][Job Market Paper, submitted to [*Journal of Economics & Management Strategy*](https://onlinelibrary.wiley.com/journal/15309134)]
  * Abstract: As franchisees in the retail and service industries become experienced and acquire local market knowledge, they are likely to own multiple franchised units. Given non (or weak) exclusive clauses in franchising contracts or industry norms, some of these multi-unit owners are affiliated with multiple franchisors. Agency and transaction cost theories, the classic theoretical framework to analyze franchising, cannot explain this type of multi-franchisor affiliation since this type of ownership would create incentive problems across franchisors. Conversely, this paper investigates whether this type of the multi-unit ownership can be explained by the exercise of market power by these franchisees when their units are geographically clustered. This paper uses data on hotels near the interstate highway exits in Texas to test this hypothesis. The results of this paper show that multi-unit owners have contracts with more than one franchisor and that multi-unit owners charge higher prices than single-unit owners. Counterfactual analysis shows that without multi-unit ownership, prices would decrease by 3.91%, on average. This price increase is associated with a volume increase of 7.52%. These results help explain why franchisors might be willing to engage in franchising contracts with franchisees that operate units associated with different franchisors.


##### Multimarket Contact in the Hotel Industry [[Draft]](Draft_MMC_8_26_19.pdf)
+ Abstract: Since Bernheim and Whinston (1990), growing number of studies have empirically examined if multimarket contact facilitates collusion in various industries (e.g., airlines, cement, movie theaters). This paper contributes this literature by investigating the effect of multimarket contacts on prices in in the hotel industry in which firms tend to closely locate in the markets, such as metropolitan areas. To data, insufficient attention has paid to such geographic areas, even though firms face competition of similar sets of rivals in different markets, even in an MSA. Based on the notion that rivals exert strong influence on firms’ prices, this paper empirically defines markets in a metropolitan hotel market by using the distance metric approach by Pinkse et al. (2002). As a result, two valid market definitions are form: rivals with 2.5 miles radius, and the fifth nearest neighbors from each hotel. With these definitions, markets are empirically formed and reduced form model analysis is conducted to evaluate the effects of multimarket contact on price. The results support that hotels with more multimarket contacts of their rivals charge higher prices under both the market definitions.

## Work in Progress
##### Multimarket Contact on Non-Price Characteristics: Using Consumer Generated Ratings on Hotels

## Publication in Management
##### [Determinant of Operating Lease in the Hotel Industry](https://www.sciencedirect.com/science/article/pii/S0278431909000346), *International Journal of Hospitality Management*, 28, December 2009 (With [SooCheong(Shawn) Jang](https://www.purdue.edu/hhs/htm/directory/faculty/jang_soocheong.html))
