---
title: "Teaching"
---

## Instructor 
### University of Michigan Ann Arbor
- Introduction to Econometrics (ECON 452): Fall 2021, Winter 2022
- Environmental and Resource Economics (ECON 370): Fall 2021, Winter 2022
- Introduction to Statistics and Econometrics II (ECON 251): Fall 2021, Winter 2022, Spring 2022


### University of Massachusetts Amherst
- Cost-Benefit Analysis (RESEC 471): Spring 2021
- Intro Statistics for Business and Economics (RESEC 212): Spring 2015, Spring 2016, Summer 2018
- Intro Resource Economics (RESEC 102): Fall 2015, Spring 2019
- The Consumer in Our Society (RESEC 161): Fall 2018
- Hunger in a Global Economy (RESEC 121): Summer 2019


## Teaching Assitant 
### Resource Economics at UMass Amherst
- Courses: Intro Statistics for Business and Economics (RESEC 212), Intermediate Statistics for Business and Economics (RESEC 213),
Industrial Organization in Resource Economics (RESEC 452), Public Policy in Private Markets (RESEC 453)

## Teaching Award
##### [Vijay Bhagavan Teaching Assistant of Distinction Award (2017)](https://www.umass.edu/resec/news/jung-hwan-koh-kelly-hellman-and-irene-mussio-win-vijay-bhagavan-and-carolyn-harper-graduate)



